/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollsNewRouteImport } from './routes/polls.new'
import { Route as PollsIdRouteImport } from './routes/polls.$id'
import { Route as PShareIdRouteImport } from './routes/p.$shareId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PollsIdResultsRouteImport } from './routes/polls.$id_.results'
import { Route as PollsIdEditRouteImport } from './routes/polls.$id_.edit'
import { Route as PollsIdAnalyticsRouteImport } from './routes/polls.$id_.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsNewRoute = PollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdRoute = PollsIdRouteImport.update({
  id: '/polls/$id',
  path: '/polls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareIdRoute = PShareIdRouteImport.update({
  id: '/p/$shareId',
  path: '/p/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdResultsRoute = PollsIdResultsRouteImport.update({
  id: '/polls/$id_/results',
  path: '/polls/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdEditRoute = PollsIdEditRouteImport.update({
  id: '/polls/$id_/edit',
  path: '/polls/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdAnalyticsRoute = PollsIdAnalyticsRouteImport.update({
  id: '/polls/$id_/analytics',
  path: '/polls/$id/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRoute
  '/polls/new': typeof PollsNewRoute
  '/polls/$id/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id/edit': typeof PollsIdEditRoute
  '/polls/$id/results': typeof PollsIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRoute
  '/polls/new': typeof PollsNewRoute
  '/polls/$id/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id/edit': typeof PollsIdEditRoute
  '/polls/$id/results': typeof PollsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRoute
  '/polls/new': typeof PollsNewRoute
  '/polls/$id_/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id_/edit': typeof PollsIdEditRoute
  '/polls/$id_/results': typeof PollsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/analytics'
    | '/polls/$id/edit'
    | '/polls/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/analytics'
    | '/polls/$id/edit'
    | '/polls/$id/results'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id_/analytics'
    | '/polls/$id_/edit'
    | '/polls/$id_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PShareIdRoute: typeof PShareIdRoute
  PollsIdRoute: typeof PollsIdRoute
  PollsNewRoute: typeof PollsNewRoute
  PollsIdAnalyticsRoute: typeof PollsIdAnalyticsRoute
  PollsIdEditRoute: typeof PollsIdEditRoute
  PollsIdResultsRoute: typeof PollsIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/new': {
      id: '/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof PollsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id': {
      id: '/polls/$id'
      path: '/polls/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof PollsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareId': {
      id: '/p/$shareId'
      path: '/p/$shareId'
      fullPath: '/p/$shareId'
      preLoaderRoute: typeof PShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id_/results': {
      id: '/polls/$id_/results'
      path: '/polls/$id/results'
      fullPath: '/polls/$id/results'
      preLoaderRoute: typeof PollsIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id_/edit': {
      id: '/polls/$id_/edit'
      path: '/polls/$id/edit'
      fullPath: '/polls/$id/edit'
      preLoaderRoute: typeof PollsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id_/analytics': {
      id: '/polls/$id_/analytics'
      path: '/polls/$id/analytics'
      fullPath: '/polls/$id/analytics'
      preLoaderRoute: typeof PollsIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PShareIdRoute: PShareIdRoute,
  PollsIdRoute: PollsIdRoute,
  PollsNewRoute: PollsNewRoute,
  PollsIdAnalyticsRoute: PollsIdAnalyticsRoute,
  PollsIdEditRoute: PollsIdEditRoute,
  PollsIdResultsRoute: PollsIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
