/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollsNewRouteImport } from './routes/polls.new'
import { Route as PollsIdRouteImport } from './routes/polls.$id'
import { Route as PShareIdRouteImport } from './routes/p.$shareId'
import { Route as PollsIdEditRouteImport } from './routes/polls.$id_.edit'
import { Route as PollsIdResultsRouteImport } from './routes/polls.$id.results'
import { Route as PollsIdAnalyticsRouteImport } from './routes/polls.$id.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsNewRoute = PollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdRoute = PollsIdRouteImport.update({
  id: '/polls/$id',
  path: '/polls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareIdRoute = PShareIdRouteImport.update({
  id: '/p/$shareId',
  path: '/p/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdEditRoute = PollsIdEditRouteImport.update({
  id: '/polls/$id_/edit',
  path: '/polls/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIdResultsRoute = PollsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PollsIdRoute,
} as any)
const PollsIdAnalyticsRoute = PollsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PollsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRouteWithChildren
  '/polls/new': typeof PollsNewRoute
  '/polls/$id/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id/results': typeof PollsIdResultsRoute
  '/polls/$id/edit': typeof PollsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRouteWithChildren
  '/polls/new': typeof PollsNewRoute
  '/polls/$id/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id/results': typeof PollsIdResultsRoute
  '/polls/$id/edit': typeof PollsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/p/$shareId': typeof PShareIdRoute
  '/polls/$id': typeof PollsIdRouteWithChildren
  '/polls/new': typeof PollsNewRoute
  '/polls/$id/analytics': typeof PollsIdAnalyticsRoute
  '/polls/$id/results': typeof PollsIdResultsRoute
  '/polls/$id_/edit': typeof PollsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/analytics'
    | '/polls/$id/results'
    | '/polls/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/analytics'
    | '/polls/$id/results'
    | '/polls/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/p/$shareId'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/analytics'
    | '/polls/$id/results'
    | '/polls/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PShareIdRoute: typeof PShareIdRoute
  PollsIdRoute: typeof PollsIdRouteWithChildren
  PollsNewRoute: typeof PollsNewRoute
  PollsIdEditRoute: typeof PollsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/new': {
      id: '/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof PollsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id': {
      id: '/polls/$id'
      path: '/polls/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof PollsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareId': {
      id: '/p/$shareId'
      path: '/p/$shareId'
      fullPath: '/p/$shareId'
      preLoaderRoute: typeof PShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id_/edit': {
      id: '/polls/$id_/edit'
      path: '/polls/$id/edit'
      fullPath: '/polls/$id/edit'
      preLoaderRoute: typeof PollsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$id/results': {
      id: '/polls/$id/results'
      path: '/results'
      fullPath: '/polls/$id/results'
      preLoaderRoute: typeof PollsIdResultsRouteImport
      parentRoute: typeof PollsIdRoute
    }
    '/polls/$id/analytics': {
      id: '/polls/$id/analytics'
      path: '/analytics'
      fullPath: '/polls/$id/analytics'
      preLoaderRoute: typeof PollsIdAnalyticsRouteImport
      parentRoute: typeof PollsIdRoute
    }
  }
}

interface PollsIdRouteChildren {
  PollsIdAnalyticsRoute: typeof PollsIdAnalyticsRoute
  PollsIdResultsRoute: typeof PollsIdResultsRoute
}

const PollsIdRouteChildren: PollsIdRouteChildren = {
  PollsIdAnalyticsRoute: PollsIdAnalyticsRoute,
  PollsIdResultsRoute: PollsIdResultsRoute,
}

const PollsIdRouteWithChildren =
  PollsIdRoute._addFileChildren(PollsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PShareIdRoute: PShareIdRoute,
  PollsIdRoute: PollsIdRouteWithChildren,
  PollsNewRoute: PollsNewRoute,
  PollsIdEditRoute: PollsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
